import axios from "axios";

const sampleResults = [
  {
    Id: "1lllee2e",
    station: "ADW",
    name: "ANDREWS",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "amber",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "green",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "ANCS",
    observation: "STN FVRS",
    theater: "American Theater",
  },
  {
    Id: "2lllee2e",
    station: "AED",
    name: "ELMENDORF",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "red",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "red",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "GFNCS",
    observation: "STN FVRS",
    theater: "Pacific Theater",
  },
  {
    Id: "3lllee2e",
    station: "CRO",
    name: "CROUGHTON",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "green",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "green",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "GFNCS",
    observation: "STN FVRS",
    theater: "European Theater",
  },
  {
    Id: "4lllee2e",
    station: "GUA",
    name: "ANDERSON",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "amber",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "red",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "GFNCS",
    observation: "STN FVRS",
    theater: "Pacific Theater",
  },
  {
    Id: "5lllee2e",
    station: "HAW",
    name: "ASCENSION",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "amber",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "green",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "GFNCS",
    observation: "STN FVRS",
    theater: "European Theater",
  },
  {
    Id: "6lllee2e",
    station: "HIK",
    name: "HICKAM",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "red",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "amber",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "ANCS",
    observation: "STN FVRS",
    theater: "Pacific Theater",
  },
  {
    Id: "7lllee2e",
    station: "ICZ",
    name: "SIGONELLA",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "green",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "green",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "ANCS",
    observation: "STN FVRS",
    theater: "European Theater",
  },
  {
    Id: "8lllee2e",
    station: "JDG",
    name: "DIEGO GARCIA",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "red",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "green",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "ANCS",
    observation: "STN FVRS",
    theater: "Pacific Theater",
  },
  {
    Id: "9lllee2e",
    station: "JNR",
    name: "PUERTO RICO",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "amber",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "amber",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "GFNCS",
    observation: "STN FVRS",
    theater: "American Theater",
  },
  {
    Id: "10lllee2e",
    station: "JTY",
    name: "YOKOTA",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "red",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "green",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "ANCS",
    observation: "STN FVRS",
    theater: "Pacific Theater",
  },
  {
    Id: "11lllee2e",
    station: "OFF",
    name: "OFFUTT",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "green",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "amber",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "GFNCS",
    observation: "STN FVRS",
    theater: "American Theater",
  },
  {
    Id: "12lllee2e",
    station: "PLA",
    name: "LAJES",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "red",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "red",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "ANCS",
    observation: "STN FVRS",
    theater: "European Theater",
  },
  {
    Id: "13lllee2e",
    station: "MCC",
    name: "WEST COAST",
    stratdesc: "TEST STRAT DESC",
    stratcolor: "green",
    scansdesc: "TEST SCANS DESC",
    scanscolor: "red",
    aledesc: "TEST ALES DESC",
    alecolor: "green",
    dtmfdesc: "TEST DTMF DESC",
    dtmfcolor: "green",
    otherdesc: "TEST OTHER DESC",
    ncs: "ANCS",
    observation: "STN FVRS",
    theater: "American Theater",
  },
];

const dev = process.env.NODE_ENV === "development";

const getStations = async () => {
  try {
    if (dev) return sampleResults;

    const data = await axios.get(
      `${process.env.REACT_APP_API}/web/lists/getbytitle('stations')/items`,
      {
        headers: {
          Accept: "application/json; odata=verbose",
        },
        withCgreenentials: true,
      }
    );

    const results = data.data.d.results;

    return results;
  } catch (error) {
    console.log(error);
    return false;
  }
};

export default getStations;
